# THE PINNACLE - image localization script (Windows PowerShell)
# Run from inside the site/ folder. Downloads all 40 images into .\images\

New-Item -ItemType Directory -Force -Path images | Out-Null

Write-Host "Downloading nasa.gov-lunar-flyby.jpg..."
Invoke-WebRequest -Uri "https://media.beehiiv.com/cdn-cgi/image/fit=scale-down,format=auto,onerror=redirect,quality=80/uploads/asset/file/0061ac62-0546-4088-b530-af44c5c8fba7/nasa.gov-lunar-flyby.jpg" -OutFile "images\nasa.gov-lunar-flyby.jpg"
Write-Host "Downloading nasa.gov-lunar-flyby.jpg..."
Invoke-WebRequest -Uri "https://media.beehiiv.com/cdn-cgi/image/fit=scale-down,format=auto,onerror=redirect,quality=80/uploads/asset/file/0061ac62-0546-4088-b530-af44c5c8fba7/nasa.gov-lunar-flyby.jpg?t=1775763379" -OutFile "images\nasa.gov-lunar-flyby.jpg"
Write-Host "Downloading videoframe_1423.png..."
Invoke-WebRequest -Uri "https://media.beehiiv.com/cdn-cgi/image/fit=scale-down,format=auto,onerror=redirect,quality=80/uploads/asset/file/8a8487ad-b849-47db-8e36-9949014e1f05/videoframe_1423.png?t=1775764280" -OutFile "images\videoframe_1423.png"
Write-Host "Downloading videoframe_29620.png..."
Invoke-WebRequest -Uri "https://media.beehiiv.com/cdn-cgi/image/fit=scale-down,format=auto,onerror=redirect,quality=80/uploads/asset/file/a7b4c14e-6401-45e1-8325-4e2caa7543e6/videoframe_29620.png?t=1775764367" -OutFile "images\videoframe_29620.png"
Write-Host "Downloading Dream-Chaser-Completes-Tow-Testing-2.jpg..."
Invoke-WebRequest -Uri "https://www.sierraspace.com/wp-content/uploads/2025/11/Dream-Chaser-Completes-Tow-Testing-2.jpg" -OutFile "images\Dream-Chaser-Completes-Tow-Testing-2.jpg"
Write-Host "Downloading hero-Reef_FullColor_ExternalHD.jpg..."
Invoke-WebRequest -Uri "https://www.sierraspace.com/wp-content/uploads/2022/04/hero-Reef_FullColor_ExternalHD.jpg" -OutFile "images\hero-Reef_FullColor_ExternalHD.jpg"
Write-Host "Downloading art002e009301_large.jpg..."
Invoke-WebRequest -Uri "https://media.beehiiv.com/cdn-cgi/image/fit=scale-down,format=auto,onerror=redirect,quality=80/uploads/asset/file/5b28c72c-44b1-4a17-a315-b11301a497fc/art002e009301_large.jpg?t=1775764919" -OutFile "images\art002e009301_large.jpg"
Write-Host "Downloading 715Brooktree-RayKappe-rearexterior.jpg..."
Invoke-WebRequest -Uri "https://media.beehiiv.com/cdn-cgi/image/fit=scale-down,format=auto,onerror=redirect,quality=80/uploads/asset/file/81209558-3a31-4db4-afc7-01719e0b5d59/715Brooktree-RayKappe-rearexterior.jpg" -OutFile "images\715Brooktree-RayKappe-rearexterior.jpg"
Write-Host "Downloading RayKappeHouse_PP_FI4.jpg..."
Invoke-WebRequest -Uri "https://media.beehiiv.com/cdn-cgi/image/fit=scale-down,format=auto,onerror=redirect,quality=80/uploads/asset/file/cc32a0c9-3a83-4e48-96f6-b7a8330dba10/RayKappeHouse_PP_FI4.jpg?t=1771018493" -OutFile "images\RayKappeHouse_PP_FI4.jpg"
Write-Host "Downloading 715Brooktree-RayKappe-office2.jpg..."
Invoke-WebRequest -Uri "https://media.beehiiv.com/cdn-cgi/image/fit=scale-down,format=auto,onerror=redirect,quality=80/uploads/asset/file/0572b8ff-9a25-4fbb-94b9-a63ad3a6e101/715Brooktree-RayKappe-office2.jpg?t=1771018569" -OutFile "images\715Brooktree-RayKappe-office2.jpg"
Write-Host "Downloading 715Brooktree-RayKappe-rearexterior.jpg..."
Invoke-WebRequest -Uri "https://media.beehiiv.com/cdn-cgi/image/fit=scale-down,format=auto,onerror=redirect,quality=80/uploads/asset/file/ccc03dfb-2160-45a8-b94f-f4a7cc2dfd7d/715Brooktree-RayKappe-rearexterior.jpg?t=1771018760" -OutFile "images\715Brooktree-RayKappe-rearexterior.jpg"
Write-Host "Downloading image.jpg..."
Invoke-WebRequest -Uri "https://media.beehiiv.com/cdn-cgi/image/fit=scale-down,format=auto,onerror=redirect,quality=80/uploads/asset/file/96699286-00a0-4a13-9986-67bf908eeaf2/image.jpg" -OutFile "images\image.jpg"
Write-Host "Downloading lady-leslie-ridley-tree-montecito-estate-front.jpg..."
Invoke-WebRequest -Uri "https://media.beehiiv.com/cdn-cgi/image/fit=scale-down,format=auto,onerror=redirect,quality=80/uploads/asset/file/177154af-ff03-4c82-a4be-d67f25a271d5/lady-leslie-ridley-tree-montecito-estate-front.jpg.jpg" -OutFile "images\lady-leslie-ridley-tree-montecito-estate-front.jpg"
Write-Host "Downloading lady-leslie-ridley-tree-montecito-estate-front.jpg..."
Invoke-WebRequest -Uri "https://media.beehiiv.com/cdn-cgi/image/fit=scale-down,format=auto,onerror=redirect,quality=80/uploads/asset/file/177154af-ff03-4c82-a4be-d67f25a271d5/lady-leslie-ridley-tree-montecito-estate-front.jpg.jpg?t=1772126368" -OutFile "images\lady-leslie-ridley-tree-montecito-estate-front.jpg"
Write-Host "Downloading montecito-luxury-estate-pool-xorin-balbes-design.jpg..."
Invoke-WebRequest -Uri "https://media.beehiiv.com/cdn-cgi/image/fit=scale-down,format=auto,onerror=redirect,quality=80/uploads/asset/file/b1aa26f6-92b9-4740-aadd-794ea6bdff2a/montecito-luxury-estate-pool-xorin-balbes-design.jpg.jpg?t=1772126515" -OutFile "images\montecito-luxury-estate-pool-xorin-balbes-design.jpg"
Write-Host "Downloading architectural-glass-atrium-204-hot-springs-road.jpg..."
Invoke-WebRequest -Uri "https://media.beehiiv.com/cdn-cgi/image/fit=scale-down,format=auto,onerror=redirect,quality=80/uploads/asset/file/d64f6e48-e7b4-4418-91db-4dda2fa39487/architectural-glass-atrium-204-hot-springs-road.jpg.jpg?t=1772126796" -OutFile "images\architectural-glass-atrium-204-hot-springs-road.jpg"
Write-Host "Downloading modern-european-kitchen-montecito-luxury-real-estate.jpg..."
Invoke-WebRequest -Uri "https://media.beehiiv.com/cdn-cgi/image/fit=scale-down,format=auto,onerror=redirect,quality=80/uploads/asset/file/9dbfe774-7d65-4c40-b410-dc20a9c4ddc4/modern-european-kitchen-montecito-luxury-real-estate.jpg.jpg?t=1772126882" -OutFile "images\modern-european-kitchen-montecito-luxury-real-estate.jpg"
Write-Host "Downloading montecito-estate-dining-room-xorin-balbes-design.jpg..."
Invoke-WebRequest -Uri "https://media.beehiiv.com/cdn-cgi/image/fit=scale-down,format=auto,onerror=redirect,quality=80/uploads/asset/file/a3622f5d-7ede-41d7-bfea-17ac3de88b68/montecito-estate-dining-room-xorin-balbes-design.jpg.jpg?t=1772127029" -OutFile "images\montecito-estate-dining-room-xorin-balbes-design.jpg"
Write-Host "Downloading designer-dining-room-custom-lighting-montecito.jpg..."
Invoke-WebRequest -Uri "https://media.beehiiv.com/cdn-cgi/image/fit=scale-down,format=auto,onerror=redirect,quality=80/uploads/asset/file/ef224be3-ef82-410c-80ce-0b2aa8d392e3/designer-dining-room-custom-lighting-montecito.jpg.jpg?t=1772126954" -OutFile "images\designer-dining-room-custom-lighting-montecito.jpg"
Write-Host "Downloading primary-suite-retreat-fireplace-montecito-mansion.jpg..."
Invoke-WebRequest -Uri "https://media.beehiiv.com/cdn-cgi/image/fit=scale-down,format=auto,onerror=redirect,quality=80/uploads/asset/file/4bf1c3a4-e180-4b4f-bde3-284e86ac6145/primary-suite-retreat-fireplace-montecito-mansion.jpg.JPG?t=1772127146" -OutFile "images\primary-suite-retreat-fireplace-montecito-mansion.jpg"
Write-Host "Downloading luxury-primary-bathroom-freestanding-tub-design.jpg..."
Invoke-WebRequest -Uri "https://media.beehiiv.com/cdn-cgi/image/fit=scale-down,format=auto,onerror=redirect,quality=80/uploads/asset/file/05599e32-b1b9-4e87-a6b6-0a4158fa0d29/luxury-primary-bathroom-freestanding-tub-design.jpg.JPG?t=1772127210" -OutFile "images\luxury-primary-bathroom-freestanding-tub-design.jpg"
Write-Host "Downloading montecito-sculpture-garden-lily-pond-landscaping.jpg..."
Invoke-WebRequest -Uri "https://media.beehiiv.com/cdn-cgi/image/fit=scale-down,format=auto,onerror=redirect,quality=80/uploads/asset/file/392c3127-e54d-4965-9729-1b0f6526ce42/montecito-sculpture-garden-lily-pond-landscaping.jpg.jpg?t=1772127580" -OutFile "images\montecito-sculpture-garden-lily-pond-landscaping.jpg"
Write-Host "Downloading love-is-bald-north-carolina-cancer-charity-logo.jpg..."
Invoke-WebRequest -Uri "https://media.beehiiv.com/cdn-cgi/image/fit=scale-down,format=auto,onerror=redirect,quality=80/uploads/asset/file/eebf9bde-d29a-4dfd-a2e8-0cbbe0dbb8b5/love-is-bald-north-carolina-cancer-charity-logo.jpg.jpg" -OutFile "images\love-is-bald-north-carolina-cancer-charity-logo.jpg"
Write-Host "Downloading love-is-bald-amy-cromartie-volleyball-tournament-nc.jpg.jpeg..."
Invoke-WebRequest -Uri "https://media.beehiiv.com/cdn-cgi/image/fit=scale-down,format=auto,onerror=redirect,quality=80/uploads/asset/file/86d28e24-170b-459e-b418-264fd1211061/love-is-bald-amy-cromartie-volleyball-tournament-nc.jpg.jpeg?t=1771974174" -OutFile "images\love-is-bald-amy-cromartie-volleyball-tournament-nc.jpg.jpeg"
Write-Host "Downloading Netflix_Chart1.png..."
Invoke-WebRequest -Uri "https://media.beehiiv.com/cdn-cgi/image/fit=scale-down,format=auto,onerror=redirect,quality=80/uploads/asset/file/eeee42b3-fbdd-4acb-bb69-3d7f67e92468/Netflix_Chart1.png" -OutFile "images\Netflix_Chart1.png"
Write-Host "Downloading Netflix_Chart1.png..."
Invoke-WebRequest -Uri "https://media.beehiiv.com/cdn-cgi/image/fit=scale-down,format=auto,onerror=redirect,quality=80/uploads/asset/file/c9a7aa05-4b7e-4854-a65e-fa60982ff65b/Netflix_Chart1.png?t=1771371000" -OutFile "images\Netflix_Chart1.png"
Write-Host "Downloading California_vineyard_and_wine_history.png..."
Invoke-WebRequest -Uri "https://media.beehiiv.com/cdn-cgi/image/fit=scale-down,format=auto,onerror=redirect,quality=80/uploads/asset/file/e2fcec11-0ddf-48b8-b8af-50351b7095ff/California_vineyard_and_wine_history.png" -OutFile "images\California_vineyard_and_wine_history.png"
Write-Host "Downloading Alexander_House_pool.jpg..."
Invoke-WebRequest -Uri "https://media.beehiiv.com/cdn-cgi/image/fit=scale-down,format=auto,onerror=redirect,quality=80/uploads/asset/file/0f711816-01fd-4eac-ad28-9f758138e887/Alexander_House_pool.jpg" -OutFile "images\Alexander_House_pool.jpg"
Write-Host "Downloading Alexander_House_pool.jpg..."
Invoke-WebRequest -Uri "https://media.beehiiv.com/cdn-cgi/image/fit=scale-down,format=auto,onerror=redirect,quality=80/uploads/asset/file/0f711816-01fd-4eac-ad28-9f758138e887/Alexander_House_pool.jpg?t=1770999299" -OutFile "images\Alexander_House_pool.jpg"
Write-Host "Downloading 5281EastElRoble1.jpg..."
Invoke-WebRequest -Uri "https://media.beehiiv.com/cdn-cgi/image/fit=scale-down,format=auto,onerror=redirect,quality=80/uploads/asset/file/d620f2b0-bec3-4616-9097-cf4bea8b8dae/5281EastElRoble1.jpg?t=1770999557" -OutFile "images\5281EastElRoble1.jpg"
Write-Host "Downloading 5281EastElRoble3.jpg..."
Invoke-WebRequest -Uri "https://media.beehiiv.com/cdn-cgi/image/fit=scale-down,format=auto,onerror=redirect,quality=80/uploads/asset/file/6fef1924-2539-4782-9948-c527b01e5f39/5281EastElRoble3.jpg?t=1770999827" -OutFile "images\5281EastElRoble3.jpg"
Write-Host "Downloading 5281EastElRoble6.jpg..."
Invoke-WebRequest -Uri "https://media.beehiiv.com/cdn-cgi/image/fit=scale-down,format=auto,onerror=redirect,quality=80/uploads/asset/file/7aead459-6b23-47a8-a592-89d9170c8d68/5281EastElRoble6.jpg?t=1770999915" -OutFile "images\5281EastElRoble6.jpg"
Write-Host "Downloading 5281EastElRoble5.jpg..."
Invoke-WebRequest -Uri "https://media.beehiiv.com/cdn-cgi/image/fit=scale-down,format=auto,onerror=redirect,quality=80/uploads/asset/file/2479ff0f-72c1-45e8-a15b-7025401da8ab/5281EastElRoble5.jpg?t=1771000063" -OutFile "images\5281EastElRoble5.jpg"
Write-Host "Downloading 5281EastElRoble11.jpg..."
Invoke-WebRequest -Uri "https://media.beehiiv.com/cdn-cgi/image/fit=scale-down,format=auto,onerror=redirect,quality=80/uploads/asset/file/bcdda68d-5996-4ec7-8466-d012e144b1a4/5281EastElRoble11.jpg?t=1770999997" -OutFile "images\5281EastElRoble11.jpg"
Write-Host "Downloading NVIDIA_stock_trading_on_TIPRANKS_platform.png..."
Invoke-WebRequest -Uri "https://media.beehiiv.com/cdn-cgi/image/fit=scale-down,format=auto,onerror=redirect,quality=80/uploads/asset/file/9d09edd8-98a3-4990-a053-f80e23cd4aa8/NVIDIA_stock_trading_on_TIPRANKS_platform.png" -OutFile "images\NVIDIA_stock_trading_on_TIPRANKS_platform.png"
Write-Host "Downloading Shattered_view_of_home_and_market_rise.png..."
Invoke-WebRequest -Uri "https://media.beehiiv.com/cdn-cgi/image/fit=scale-down,format=auto,onerror=redirect,quality=80/uploads/asset/file/4863aa6e-33e6-4172-81a1-0bebd9242bd3/Shattered_view_of_home_and_market_rise.png" -OutFile "images\Shattered_view_of_home_and_market_rise.png"
Write-Host "Downloading Buffett_vs._Buffett.png..."
Invoke-WebRequest -Uri "https://media.beehiiv.com/cdn-cgi/image/fit=scale-down,format=auto,onerror=redirect,quality=80/uploads/asset/file/3ac9e9fe-ab2e-4742-adee-65cb7dec8049/Buffett_vs._Buffett.png" -OutFile "images\Buffett_vs._Buffett.png"
Write-Host "Downloading xpo-stock-price.png..."
Invoke-WebRequest -Uri "https://media.beehiiv.com/cdn-cgi/image/fit=scale-down,format=auto,onerror=redirect,quality=80/uploads/asset/file/6c3de8ec-7228-440f-ba09-36468a4263e2/xpo-stock-price.png" -OutFile "images\xpo-stock-price.png"
Write-Host "Downloading xpo-stock-price.png..."
Invoke-WebRequest -Uri "https://media.beehiiv.com/cdn-cgi/image/fit=scale-down,format=auto,onerror=redirect,quality=80/uploads/asset/file/6c3de8ec-7228-440f-ba09-36468a4263e2/xpo-stock-price.png?t=1769714250" -OutFile "images\xpo-stock-price.png"

Write-Host ""
Write-Host "Done"